import type { CalculatorData, DailyAction, Badge } from '../types';

export const DEFAULT_CALCULATOR_DATA: CalculatorData = {
  carKm: 160,
  carType: 'compact',
  transitHours: 2,
  flightsShort: 2,
  flightsLong: 0,
  electricityKwh: 300,
  heatingSource: 'gas',
  gasBill: 2500,
  diet: 'low-meat',
  waste: 'average',
  shoppingHabits: 'average',
  electronics: 'average',
};

export const AVAILABLE_ACTIONS: DailyAction[] = [
  {
    id: 'walk_cycle',
    category: 'transport',
    title: 'Walk or Cycle',
    description: 'Walk or bike instead of driving a car for short trips.',
    points: 25,
    co2Offset: 2.4,
    icon: 'bike',
  },
  {
    id: 'plant_meal',
    category: 'food',
    title: 'Plant-Based Meal',
    description: 'Eat a fully plant-based meal today (no meat or dairy).',
    points: 20,
    co2Offset: 1.5,
    icon: 'salad',
  },
  {
    id: 'shorter_shower',
    category: 'energy',
    title: 'Shorter Shower',
    description: 'Limit your shower to under 5 minutes to save water and energy.',
    points: 15,
    co2Offset: 0.5,
    icon: 'shower',
  },
  {
    id: 'line_dry',
    category: 'energy',
    title: 'Line Dry Clothes',
    description: 'Air dry laundry instead of using a high-energy tumble dryer.',
    points: 15,
    co2Offset: 0.8,
    icon: 'wind',
  },
  {
    id: 'unplug_idle',
    category: 'energy',
    title: 'Unplug Standby Devices',
    description: 'Turn off power strips and unplug appliances not in use.',
    points: 10,
    co2Offset: 0.3,
    icon: 'power',
  },
  {
    id: 'no_food_waste',
    category: 'waste',
    title: 'Zero Food Waste',
    description: 'Finish all meals and properly store leftovers to avoid throwing food away.',
    points: 15,
    co2Offset: 0.7,
    icon: 'trash',
  },
  {
    id: 'second_hand',
    category: 'shopping',
    title: 'Buy Second-Hand/Local',
    description: 'Buy local produce or thrift clothing/items instead of new ones.',
    points: 25,
    co2Offset: 1.8,
    icon: 'shopping-bag',
  },
  {
    id: 'lights_off',
    category: 'energy',
    title: 'Smart Lighting',
    description: 'Turn off lights when leaving rooms and use natural light when possible.',
    points: 10,
    co2Offset: 0.2,
    icon: 'lightbulb',
  },
  {
    id: 'reusable_cup',
    category: 'waste',
    title: 'Reusable Container',
    description: 'Use reusable water bottles, coffee cups, or grocery bags today.',
    points: 10,
    co2Offset: 0.2,
    icon: 'cup-soda',
  },
];

export const INITIAL_BADGES: Badge[] = [
  {
    id: 'first_calc',
    title: 'Climate Conscious',
    description: 'Complete the carbon footprint questionnaire.',
    requirement: 'Questionnaire completed',
    iconName: 'Compass',
    unlocked: false,
  },
  {
    id: 'first_action',
    title: 'First Step',
    description: 'Log your first green daily action.',
    requirement: 'Log 1 daily action',
    iconName: 'Footprints',
    unlocked: false,
  },
  {
    id: 'streak_3',
    title: 'Eco Habit',
    description: 'Maintain a 3-day active streak.',
    requirement: '3-day streak',
    iconName: 'Flame',
    unlocked: false,
  },
  {
    id: 'streak_7',
    title: 'Climate Champion',
    description: 'Maintain a 7-day active streak.',
    requirement: '7-day streak',
    iconName: 'Zap',
    unlocked: false,
  },
  {
    id: 'offset_10',
    title: 'Carbon Cutter',
    description: 'Offset a total of 10kg of CO2 emissions.',
    requirement: '10kg offset',
    iconName: 'Leaf',
    unlocked: false,
  },
  {
    id: 'offset_50',
    title: 'Green Guardian',
    description: 'Offset a total of 50kg of CO2 emissions.',
    requirement: '50kg offset',
    iconName: 'Shield',
    unlocked: false,
  },
  {
    id: 'diversity_hero',
    title: 'Green All-Rounder',
    description: 'Perform at least one action from all 5 categories.',
    requirement: '5 categories logged',
    iconName: 'Layers',
    unlocked: false,
  },
];
